version: '3'
services:
  api-socket-devchat-mongo:
    container_name: devchat
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: docker
      MONGO_INITDB_ROOT_PASSWORD: docker
    volumes:
      - ./data:/data/db
